### ISSUE TITLE
Uniquely identify existing issues by title before editing issue descriptions

### ISSUE THREAD

**Issue by agriyakhetarpal** [xarray-contrib/issue-from-pytest-log#34]
## Description

This feature request is as discussed in #2. This addition would be beneficial for cases where multiple issues are to be opened through multiple workflows or through multiple jobs in a single workflow (or through a matrix that creates those jobs). Therefore, issues can then be identified with the issue title that is being served as a user-provided input to the action, and just those issues' descriptions will be modified.

A very crude example:

```yaml

on:
  schedule
  ...

jobs:
  test:
    strategy:
      matrix:
        os: [macos-13, macos-14]

    steps:
    ...
    - uses: xarray-contrib/issue-from-pytest-log
      with:
        log-path: "${{ matrix.os }} tests failed ⚠️"
```

will create two separate issues (this may or may not be useful, but there are other contexts such as `github.ref` or `github.run_id` that are probably useful)

## Possible implementation

This section of `action.yml` below

https://github.com/xarray-contrib/issue-from-pytest-log/blob/de159a645490f936de66308e9b5e0fba4727d6a9/action.yaml#L59-L73

can be modified to run a different GraphQL query that searches for issues with the

```javascript
const title = "${{ inputs.issue-title }}"
```

variable, and create/edit just those issues.

## Additional context

N/A
